apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "booking-service.fullname" . }}
  labels:
    app: booking-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
{{- with .Values.env }}
{{- range $key, $value := . }}
            - name: {{ $key }}
              value: "{{ $value }}"
{{- end }}
{{- end }}
{{- with .Values.envFromSecret }}
{{- range . }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .secretKey }}
{{- end }}
{{- end }}
