apiVersion: v1
kind: Service
metadata:
  name: {{ include "booking-service.fullname" . }}
  labels:
    app: booking-service
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32725
  selector:
    app: booking-service
