version: '3.8'

services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      - BOOKING_SERVICE_URL=http://booking_service:8000
      - INVENTORY_SERVICE_URL=http://inventory_service:8000
    depends_on:
      - booking_service
      - inventory_service

  booking_service:
    build: ./booking_service
    volumes:
      - ./booking_service/app:/app
    ports:
      - "8001:8000" # Expose for direct testing if needed

  inventory_service:
    build: ./inventory_service
    volumes:
      - ./inventory_service/app:/app
    ports:
      - "8002:8000" # Expose for direct testing if needed 