version: '3.8'

services:
  booking_service:
    build:
      context: ./booking_service
    container_name: booking_service
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - backend

  inventory_service:
    build:
      context: ./inventory_service
    container_name: inventory_service
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - backend

networks:
  backend:
    driver: bridge 