version: '3.8'

services:
  booking_service:
    build:
      context: ./booking_service
    container_name: booking_service
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SENTRY_DSN=${SENTRY_DSN}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    networks:
      - backend

  inventory_service:
    build:
      context: ./inventory_service
    container_name: inventory_service
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SENTRY_DSN=${SENTRY_DSN}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317

    networks:
      - backend

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    user: "0:0"
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
      # - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: ["--config=/etc/otelcol/config.yaml"]
    environment:
      - GRAFANA_CLOUD_INSTANCE_ID=${GRAFANA_CLOUD_INSTANCE_ID}
      - GRAFANA_CLOUD_OTLP_ENDPOINT=${GRAFANA_CLOUD_OTLP_ENDPOINT}
      - GRAFANA_CLOUD_API_KEY=${GRAFANA_CLOUD_API_KEY}
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - booking_service
      - inventory_service

    networks:
      - backend



networks:
  backend:
    driver: bridge 