replicaCount: 3
image:
  tag: "826ad8839f22bedf7aff0829579f3704458e123a"
service:
  type: ClusterIP
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
podAnnotations:
  environment: prod
  linkerd.io/inject: "enabled"
podLabels:
  environment: prod 