apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inventory-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/crypticseeds/Hotel-Inventory-Booking-System.git'
    targetRevision: HEAD
    path: helm-charts/inventory-service  # or wherever your manifests/Helm chart is
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: inventory
  syncPolicy:
    automated:
      prune: true
      selfHeal: true